# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\gui\design.ui'
#
# Created: Fri Mar 20 15:46:47 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MK_DCC(object):
    def setupUi(self, MK_DCC):
        MK_DCC.setObjectName("MK_DCC")
        MK_DCC.resize(282, 426)
        self.centralwidget = QtGui.QWidget(MK_DCC)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.maya_tab = QtGui.QWidget()
        self.maya_tab.setObjectName("maya_tab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.maya_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_4 = QtGui.QGroupBox(self.maya_tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_9.addWidget(self.pushButton_2)
        self.radioButton = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_9.addWidget(self.radioButton)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.maya_tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.maya_tab, "")
        self.houdini_tab = QtGui.QWidget()
        self.houdini_tab.setObjectName("houdini_tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.houdini_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.houdini_tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.houdini_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.spinBox = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_6.addWidget(self.spinBox)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.houdini_tab, "")
        self.cfg_tab = QtGui.QWidget()
        self.cfg_tab.setObjectName("cfg_tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.cfg_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.themes_grpBox = QtGui.QGroupBox(self.cfg_tab)
        self.themes_grpBox.setObjectName("themes_grpBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.themes_grpBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.theme_comboBox = QtGui.QComboBox(self.themes_grpBox)
        self.theme_comboBox.setObjectName("theme_comboBox")
        self.theme_comboBox.addItem("")
        self.theme_comboBox.addItem("")
        self.theme_comboBox.addItem("")
        self.theme_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.theme_comboBox)
        self.verticalLayout_4.addWidget(self.themes_grpBox)
        self.misc_grpBox = QtGui.QGroupBox(self.cfg_tab)
        self.misc_grpBox.setObjectName("misc_grpBox")
        self.verticalLayout_4.addWidget(self.misc_grpBox)
        self.tabWidget.addTab(self.cfg_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MK_DCC.setCentralWidget(self.centralwidget)

        self.retranslateUi(MK_DCC)
        self.tabWidget.setCurrentIndex(0)
        self.theme_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MK_DCC)

    def retranslateUi(self, MK_DCC):
        MK_DCC.setWindowTitle(QtGui.QApplication.translate("MK_DCC", "miniTools3", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MK_DCC", "UDIM", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MK_DCC", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MK_DCC", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MK_DCC", "LEGACY", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MK_DCC", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.maya_tab), QtGui.QApplication.translate("MK_DCC", "maya", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MK_DCC", "SOLARIS", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("MK_DCC", "LineEdit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MK_DCC", "PDG", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox.setPrefix(QtGui.QApplication.translate("MK_DCC", "$ ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.houdini_tab), QtGui.QApplication.translate("MK_DCC", "houdini", None, QtGui.QApplication.UnicodeUTF8))
        self.themes_grpBox.setTitle(QtGui.QApplication.translate("MK_DCC", "THEMES", None, QtGui.QApplication.UnicodeUTF8))
        self.theme_comboBox.setItemText(0, QtGui.QApplication.translate("MK_DCC", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.theme_comboBox.setItemText(1, QtGui.QApplication.translate("MK_DCC", "Aqua", None, QtGui.QApplication.UnicodeUTF8))
        self.theme_comboBox.setItemText(2, QtGui.QApplication.translate("MK_DCC", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.theme_comboBox.setItemText(3, QtGui.QApplication.translate("MK_DCC", "Ubuntu", None, QtGui.QApplication.UnicodeUTF8))
        self.misc_grpBox.setTitle(QtGui.QApplication.translate("MK_DCC", "MISC.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cfg_tab), QtGui.QApplication.translate("MK_DCC", "cfg", None, QtGui.QApplication.UnicodeUTF8))

