# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\dev\git\mk_dcc/src/gui/app/setDressMaster/ui.ui'
#
# Created: Wed Oct 14 09:54:37 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 636)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.central_widget_layout = QtGui.QVBoxLayout(self.centralwidget)
        self.central_widget_layout.setObjectName("central_widget_layout")
        self.phys_painter_main_group_box = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phys_painter_main_group_box.sizePolicy().hasHeightForWidth())
        self.phys_painter_main_group_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.phys_painter_main_group_box.setFont(font)
        self.phys_painter_main_group_box.setStyleSheet("")
        self.phys_painter_main_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.phys_painter_main_group_box.setCheckable(True)
        self.phys_painter_main_group_box.setObjectName("phys_painter_main_group_box")
        self.phys_painter_group_box_layout = QtGui.QVBoxLayout(self.phys_painter_main_group_box)
        self.phys_painter_group_box_layout.setObjectName("phys_painter_group_box_layout")
        self.PP_load_selection_grid_layout = QtGui.QGridLayout()
        self.PP_load_selection_grid_layout.setObjectName("PP_load_selection_grid_layout")
        self.phys_painter_group_box_layout.addLayout(self.PP_load_selection_grid_layout)
        self.PP_dyn_parms_child_group_box = QtGui.QGroupBox(self.phys_painter_main_group_box)
        self.PP_dyn_parms_child_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.PP_dyn_parms_child_group_box.setCheckable(True)
        self.PP_dyn_parms_child_group_box.setObjectName("PP_dyn_parms_child_group_box")
        self.PP_dynamic_parameters_grid_layout = QtGui.QGridLayout(self.PP_dyn_parms_child_group_box)
        self.PP_dynamic_parameters_grid_layout.setObjectName("PP_dynamic_parameters_grid_layout")
        self.phys_painter_group_box_layout.addWidget(self.PP_dyn_parms_child_group_box)
        self.PP_setup_mash_network_btn = QtGui.QPushButton(self.phys_painter_main_group_box)
        self.PP_setup_mash_network_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.PP_setup_mash_network_btn.setStyleSheet("font-size: 12px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/baseline_wb_iridescent_white_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PP_setup_mash_network_btn.setIcon(icon)
        self.PP_setup_mash_network_btn.setIconSize(QtCore.QSize(24, 24))
        self.PP_setup_mash_network_btn.setObjectName("PP_setup_mash_network_btn")
        self.phys_painter_group_box_layout.addWidget(self.PP_setup_mash_network_btn)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.PP_toggle_interactive_playback_btn = QtGui.QToolButton(self.phys_painter_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_toggle_interactive_playback_btn.sizePolicy().hasHeightForWidth())
        self.PP_toggle_interactive_playback_btn.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/baseline_play_circle_outline_white_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PP_toggle_interactive_playback_btn.setIcon(icon1)
        self.PP_toggle_interactive_playback_btn.setIconSize(QtCore.QSize(32, 32))
        self.PP_toggle_interactive_playback_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.PP_toggle_interactive_playback_btn.setObjectName("PP_toggle_interactive_playback_btn")
        self.gridLayout.addWidget(self.PP_toggle_interactive_playback_btn, 0, 2, 1, 1)
        self.PP_show_paint_node_btn = QtGui.QToolButton(self.phys_painter_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_show_paint_node_btn.sizePolicy().hasHeightForWidth())
        self.PP_show_paint_node_btn.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/baseline_brush_white_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PP_show_paint_node_btn.setIcon(icon2)
        self.PP_show_paint_node_btn.setIconSize(QtCore.QSize(32, 32))
        self.PP_show_paint_node_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.PP_show_paint_node_btn.setObjectName("PP_show_paint_node_btn")
        self.gridLayout.addWidget(self.PP_show_paint_node_btn, 0, 1, 1, 1)
        self.PP_reset_playback_btn = QtGui.QToolButton(self.phys_painter_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_reset_playback_btn.sizePolicy().hasHeightForWidth())
        self.PP_reset_playback_btn.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/baseline_exposure_zero_white_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PP_reset_playback_btn.setIcon(icon3)
        self.PP_reset_playback_btn.setIconSize(QtCore.QSize(32, 32))
        self.PP_reset_playback_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.PP_reset_playback_btn.setObjectName("PP_reset_playback_btn")
        self.gridLayout.addWidget(self.PP_reset_playback_btn, 0, 0, 1, 1)
        self.PP_show_instancer_node_btn = QtGui.QToolButton(self.phys_painter_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_show_instancer_node_btn.sizePolicy().hasHeightForWidth())
        self.PP_show_instancer_node_btn.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/baseline_list_alt_white_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PP_show_instancer_node_btn.setIcon(icon4)
        self.PP_show_instancer_node_btn.setIconSize(QtCore.QSize(32, 32))
        self.PP_show_instancer_node_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.PP_show_instancer_node_btn.setObjectName("PP_show_instancer_node_btn")
        self.gridLayout.addWidget(self.PP_show_instancer_node_btn, 1, 0, 1, 1)
        self.PP_bake_current_btn = QtGui.QToolButton(self.phys_painter_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_bake_current_btn.sizePolicy().hasHeightForWidth())
        self.PP_bake_current_btn.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/baseline_save_alt_white_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PP_bake_current_btn.setIcon(icon5)
        self.PP_bake_current_btn.setIconSize(QtCore.QSize(32, 32))
        self.PP_bake_current_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.PP_bake_current_btn.setObjectName("PP_bake_current_btn")
        self.gridLayout.addWidget(self.PP_bake_current_btn, 1, 1, 1, 1)
        self.PP_show_all_baked_btn = QtGui.QToolButton(self.phys_painter_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_show_all_baked_btn.sizePolicy().hasHeightForWidth())
        self.PP_show_all_baked_btn.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/baseline_waves_white_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PP_show_all_baked_btn.setIcon(icon6)
        self.PP_show_all_baked_btn.setIconSize(QtCore.QSize(32, 32))
        self.PP_show_all_baked_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.PP_show_all_baked_btn.setObjectName("PP_show_all_baked_btn")
        self.gridLayout.addWidget(self.PP_show_all_baked_btn, 1, 2, 1, 1)
        self.phys_painter_group_box_layout.addLayout(self.gridLayout)
        self.PP_delete_all_setup_btn = QtGui.QPushButton(self.phys_painter_main_group_box)
        self.PP_delete_all_setup_btn.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/baseline_clear_white_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PP_delete_all_setup_btn.setIcon(icon7)
        self.PP_delete_all_setup_btn.setIconSize(QtCore.QSize(24, 24))
        self.PP_delete_all_setup_btn.setObjectName("PP_delete_all_setup_btn")
        self.phys_painter_group_box_layout.addWidget(self.PP_delete_all_setup_btn)
        self.central_widget_layout.addWidget(self.phys_painter_main_group_box)
        self.swap_master_main_group_box = QtGui.QGroupBox(self.centralwidget)
        self.swap_master_main_group_box.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swap_master_main_group_box.sizePolicy().hasHeightForWidth())
        self.swap_master_main_group_box.setSizePolicy(sizePolicy)
        self.swap_master_main_group_box.setStyleSheet("")
        self.swap_master_main_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.swap_master_main_group_box.setCheckable(True)
        self.swap_master_main_group_box.setObjectName("swap_master_main_group_box")
        self.swap_master_group_box_layout = QtGui.QVBoxLayout(self.swap_master_main_group_box)
        self.swap_master_group_box_layout.setObjectName("swap_master_group_box_layout")
        self.groupBox_3 = QtGui.QGroupBox(self.swap_master_main_group_box)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.swap_master_group_box_layout.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.swap_master_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.SM_load_trace_components_grid_layout = QtGui.QGridLayout()
        self.SM_load_trace_components_grid_layout.setObjectName("SM_load_trace_components_grid_layout")
        self.verticalLayout.addLayout(self.SM_load_trace_components_grid_layout)
        self.swap_master_group_box_layout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.swap_master_main_group_box)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SM_load_substitute_grid_layout = QtGui.QGridLayout()
        self.SM_load_substitute_grid_layout.setObjectName("SM_load_substitute_grid_layout")
        self.verticalLayout_2.addLayout(self.SM_load_substitute_grid_layout)
        self.swap_master_group_box_layout.addWidget(self.groupBox_2)
        self.pushButton = QtGui.QPushButton(self.swap_master_main_group_box)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton.setStyleSheet("font-size: 12px;")
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.swap_master_group_box_layout.addWidget(self.pushButton)
        self.central_widget_layout.addWidget(self.swap_master_main_group_box)
        self.restore_instancing_group_box = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restore_instancing_group_box.sizePolicy().hasHeightForWidth())
        self.restore_instancing_group_box.setSizePolicy(sizePolicy)
        self.restore_instancing_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.restore_instancing_group_box.setObjectName("restore_instancing_group_box")
        self.restore_instancing_group_box_layout = QtGui.QVBoxLayout(self.restore_instancing_group_box)
        self.restore_instancing_group_box_layout.setObjectName("restore_instancing_group_box_layout")
        self.central_widget_layout.addWidget(self.restore_instancing_group_box)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Set Dress Master", None, QtGui.QApplication.UnicodeUTF8))
        self.phys_painter_main_group_box.setTitle(QtGui.QApplication.translate("MainWindow", "PHYSX PAINTER", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_dyn_parms_child_group_box.setTitle(QtGui.QApplication.translate("MainWindow", "Dynamics Parameter Preset", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_setup_mash_network_btn.setText(QtGui.QApplication.translate("MainWindow", "Setup MASH Network", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_toggle_interactive_playback_btn.setText(QtGui.QApplication.translate("MainWindow", "Interactive Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_show_paint_node_btn.setText(QtGui.QApplication.translate("MainWindow", "Show Paint Node", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_reset_playback_btn.setText(QtGui.QApplication.translate("MainWindow", "Go to Time Zero", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_show_instancer_node_btn.setText(QtGui.QApplication.translate("MainWindow", "Show Instancer Node", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_bake_current_btn.setText(QtGui.QApplication.translate("MainWindow", "Bake Current", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_show_all_baked_btn.setText(QtGui.QApplication.translate("MainWindow", "Show All Baked", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_delete_all_setup_btn.setText(QtGui.QApplication.translate("MainWindow", "Delete All Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.swap_master_main_group_box.setTitle(QtGui.QApplication.translate("MainWindow", "SWAP MASTER", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Prep", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Explode Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Group by Num of Vertices", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Status Quo\'s Representative", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Trace Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Vertex", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Edge", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "Face", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Substitute Input", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Swap Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.restore_instancing_group_box.setTitle(QtGui.QApplication.translate("MainWindow", "RESTORE INSTANCING", None, QtGui.QApplication.UnicodeUTF8))

from src.gui.app.setDressMaster import resources_rc_qt4
