# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\dev\git\mk_dcc/src/gui/app/setDressMaster/ui.ui'
#
# Created: Sun Oct 11 06:34:01 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(405, 365)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.central_widget_layout = QtGui.QVBoxLayout(self.centralwidget)
        self.central_widget_layout.setObjectName("central_widget_layout")
        self.phys_painter_main_group_box = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.phys_painter_main_group_box.setFont(font)
        self.phys_painter_main_group_box.setStyleSheet("")
        self.phys_painter_main_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.phys_painter_main_group_box.setObjectName("phys_painter_main_group_box")
        self.phys_painter_group_box_layout = QtGui.QVBoxLayout(self.phys_painter_main_group_box)
        self.phys_painter_group_box_layout.setObjectName("phys_painter_group_box_layout")
        self.PP_load_selection_grid_layout = QtGui.QGridLayout()
        self.PP_load_selection_grid_layout.setObjectName("PP_load_selection_grid_layout")
        self.phys_painter_group_box_layout.addLayout(self.PP_load_selection_grid_layout)
        self.PP_dyn_parms_child_group_box = QtGui.QGroupBox(self.phys_painter_main_group_box)
        self.PP_dyn_parms_child_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.PP_dyn_parms_child_group_box.setCheckable(True)
        self.PP_dyn_parms_child_group_box.setObjectName("PP_dyn_parms_child_group_box")
        self.phys_painter_dynamic_parameters_grid_layout = QtGui.QGridLayout(self.PP_dyn_parms_child_group_box)
        self.phys_painter_dynamic_parameters_grid_layout.setObjectName("phys_painter_dynamic_parameters_grid_layout")
        self.phys_painter_group_box_layout.addWidget(self.PP_dyn_parms_child_group_box)
        self.PP_setup_mash_network_btn = QtGui.QPushButton(self.phys_painter_main_group_box)
        self.PP_setup_mash_network_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.PP_setup_mash_network_btn.setObjectName("PP_setup_mash_network_btn")
        self.phys_painter_group_box_layout.addWidget(self.PP_setup_mash_network_btn)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PP_reset_playback_btn = QtGui.QToolButton(self.phys_painter_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_reset_playback_btn.sizePolicy().hasHeightForWidth())
        self.PP_reset_playback_btn.setSizePolicy(sizePolicy)
        self.PP_reset_playback_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.PP_reset_playback_btn.setObjectName("PP_reset_playback_btn")
        self.horizontalLayout_2.addWidget(self.PP_reset_playback_btn)
        self.PP_show_paint_node_btn = QtGui.QToolButton(self.phys_painter_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_show_paint_node_btn.sizePolicy().hasHeightForWidth())
        self.PP_show_paint_node_btn.setSizePolicy(sizePolicy)
        self.PP_show_paint_node_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.PP_show_paint_node_btn.setObjectName("PP_show_paint_node_btn")
        self.horizontalLayout_2.addWidget(self.PP_show_paint_node_btn)
        self.PP_toggle_interactive_playback_btn = QtGui.QToolButton(self.phys_painter_main_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PP_toggle_interactive_playback_btn.sizePolicy().hasHeightForWidth())
        self.PP_toggle_interactive_playback_btn.setSizePolicy(sizePolicy)
        self.PP_toggle_interactive_playback_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.PP_toggle_interactive_playback_btn.setObjectName("PP_toggle_interactive_playback_btn")
        self.horizontalLayout_2.addWidget(self.PP_toggle_interactive_playback_btn)
        self.phys_painter_group_box_layout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtGui.QPushButton(self.phys_painter_main_group_box)
        self.pushButton.setEnabled(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.phys_painter_main_group_box)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.PP_delete_all_setup_btn = QtGui.QPushButton(self.phys_painter_main_group_box)
        self.PP_delete_all_setup_btn.setEnabled(True)
        self.PP_delete_all_setup_btn.setObjectName("PP_delete_all_setup_btn")
        self.horizontalLayout.addWidget(self.PP_delete_all_setup_btn)
        self.phys_painter_group_box_layout.addLayout(self.horizontalLayout)
        self.central_widget_layout.addWidget(self.phys_painter_main_group_box)
        self.swap_master_group_box = QtGui.QGroupBox(self.centralwidget)
        self.swap_master_group_box.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swap_master_group_box.sizePolicy().hasHeightForWidth())
        self.swap_master_group_box.setSizePolicy(sizePolicy)
        self.swap_master_group_box.setStyleSheet("")
        self.swap_master_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.swap_master_group_box.setObjectName("swap_master_group_box")
        self.swap_master_group_box_layout = QtGui.QVBoxLayout(self.swap_master_group_box)
        self.swap_master_group_box_layout.setObjectName("swap_master_group_box_layout")
        self.central_widget_layout.addWidget(self.swap_master_group_box)
        self.restore_instancing_group_box = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restore_instancing_group_box.sizePolicy().hasHeightForWidth())
        self.restore_instancing_group_box.setSizePolicy(sizePolicy)
        self.restore_instancing_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.restore_instancing_group_box.setObjectName("restore_instancing_group_box")
        self.restore_instancing_group_box_layout = QtGui.QVBoxLayout(self.restore_instancing_group_box)
        self.restore_instancing_group_box_layout.setObjectName("restore_instancing_group_box_layout")
        self.central_widget_layout.addWidget(self.restore_instancing_group_box)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Set Dress Master", None, QtGui.QApplication.UnicodeUTF8))
        self.phys_painter_main_group_box.setTitle(QtGui.QApplication.translate("MainWindow", "PHYSX PAINTER", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_dyn_parms_child_group_box.setTitle(QtGui.QApplication.translate("MainWindow", "Dynamics Parameter Preset", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_setup_mash_network_btn.setText(QtGui.QApplication.translate("MainWindow", "Setup MASH Network", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_reset_playback_btn.setText(QtGui.QApplication.translate("MainWindow", "Go to Time Zero", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_show_paint_node_btn.setText(QtGui.QApplication.translate("MainWindow", "Show Placer Node", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_toggle_interactive_playback_btn.setText(QtGui.QApplication.translate("MainWindow", "Interactive Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Show Instancer Node", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Bake Current", None, QtGui.QApplication.UnicodeUTF8))
        self.PP_delete_all_setup_btn.setText(QtGui.QApplication.translate("MainWindow", "Delete All Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.swap_master_group_box.setTitle(QtGui.QApplication.translate("MainWindow", "SWAP MASTER", None, QtGui.QApplication.UnicodeUTF8))
        self.restore_instancing_group_box.setTitle(QtGui.QApplication.translate("MainWindow", "RESTORE INSTANCING", None, QtGui.QApplication.UnicodeUTF8))

