# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\vsTools2\SPD\python\asset\tools\default_external_tools\ttStamper\ui\ttStamper.ui',
# licensing of 'C:\vsTools2\SPD\python\asset\tools\default_external_tools\ttStamper\ui\ttStamper.ui' applies.
#
# Created: Fri Mar 20 14:42:32 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ttStamperWindow(object):
    def setupUi(self, ttStamperWindow):
        ttStamperWindow.setObjectName("ttStamperWindow")
        ttStamperWindow.resize(359, 781)
        ttStamperWindow.setMinimumSize(QtCore.QSize(0, 0))
        ttStamperWindow.setWindowOpacity(1.0)
        self.centralWdg = QtWidgets.QWidget(ttStamperWindow)
        self.centralWdg.setObjectName("centralWdg")
        self.main_VLayout = QtWidgets.QVBoxLayout(self.centralWdg)
        self.main_VLayout.setSpacing(2)
        self.main_VLayout.setContentsMargins(0, 2, 0, 0)
        self.main_VLayout.setObjectName("main_VLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralWdg)
        self.mainTabWidget.setMaximumSize(QtCore.QSize(16777215, 1080))
        self.mainTabWidget.setTabsClosable(False)
        self.mainTabWidget.setMovable(False)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.basic_tab = QtWidgets.QWidget()
        self.basic_tab.setObjectName("basic_tab")
        self.basic_tab_VLayout = QtWidgets.QVBoxLayout(self.basic_tab)
        self.basic_tab_VLayout.setContentsMargins(3, -1, 3, -1)
        self.basic_tab_VLayout.setObjectName("basic_tab_VLayout")
        self.basicTemplate_grpBx = QtWidgets.QGroupBox(self.basic_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicTemplate_grpBx.sizePolicy().hasHeightForWidth())
        self.basicTemplate_grpBx.setSizePolicy(sizePolicy)
        self.basicTemplate_grpBx.setObjectName("basicTemplate_grpBx")
        self.basicTemplate_grpBx_HLayout = QtWidgets.QHBoxLayout(self.basicTemplate_grpBx)
        self.basicTemplate_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.basicTemplate_grpBx_HLayout.setObjectName("basicTemplate_grpBx_HLayout")
        self.basicTemplate_listWdg = TTSListWidget(self.basicTemplate_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicTemplate_listWdg.sizePolicy().hasHeightForWidth())
        self.basicTemplate_listWdg.setSizePolicy(sizePolicy)
        self.basicTemplate_listWdg.setMinimumSize(QtCore.QSize(0, 0))
        self.basicTemplate_listWdg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.basicTemplate_listWdg.setAcceptDrops(True)
        self.basicTemplate_listWdg.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.basicTemplate_listWdg.setObjectName("basicTemplate_listWdg")
        self.basicTemplate_grpBx_HLayout.addWidget(self.basicTemplate_listWdg)
        self.basicTemplate_removeBtn = QtWidgets.QPushButton(self.basicTemplate_grpBx)
        self.basicTemplate_removeBtn.setEnabled(True)
        self.basicTemplate_removeBtn.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.basicTemplate_removeBtn.setFont(font)
        self.basicTemplate_removeBtn.setStyleSheet("")
        self.basicTemplate_removeBtn.setObjectName("basicTemplate_removeBtn")
        self.basicTemplate_grpBx_HLayout.addWidget(self.basicTemplate_removeBtn)
        self.basic_tab_VLayout.addWidget(self.basicTemplate_grpBx)
        self.basicSrc_grpBx = QtWidgets.QGroupBox(self.basic_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicSrc_grpBx.sizePolicy().hasHeightForWidth())
        self.basicSrc_grpBx.setSizePolicy(sizePolicy)
        self.basicSrc_grpBx.setObjectName("basicSrc_grpBx")
        self.basicSrc_grpBx_HLayout = QtWidgets.QHBoxLayout(self.basicSrc_grpBx)
        self.basicSrc_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.basicSrc_grpBx_HLayout.setObjectName("basicSrc_grpBx_HLayout")
        self.basicSrc_listWdg = TTSListWidget(self.basicSrc_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicSrc_listWdg.sizePolicy().hasHeightForWidth())
        self.basicSrc_listWdg.setSizePolicy(sizePolicy)
        self.basicSrc_listWdg.setAcceptDrops(True)
        self.basicSrc_listWdg.setObjectName("basicSrc_listWdg")
        self.basicSrc_grpBx_HLayout.addWidget(self.basicSrc_listWdg)
        self.basicSrc_resetBtn = QtWidgets.QPushButton(self.basicSrc_grpBx)
        self.basicSrc_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.basicSrc_resetBtn.setFont(font)
        self.basicSrc_resetBtn.setStyleSheet("color: red")
        self.basicSrc_resetBtn.setObjectName("basicSrc_resetBtn")
        self.basicSrc_grpBx_HLayout.addWidget(self.basicSrc_resetBtn)
        self.basic_tab_VLayout.addWidget(self.basicSrc_grpBx)
        self.custom_grpBx = QtWidgets.QGroupBox(self.basic_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custom_grpBx.sizePolicy().hasHeightForWidth())
        self.custom_grpBx.setSizePolicy(sizePolicy)
        self.custom_grpBx.setObjectName("custom_grpBx")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.custom_grpBx)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text1_grpBx = QtWidgets.QGroupBox(self.custom_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text1_grpBx.sizePolicy().hasHeightForWidth())
        self.text1_grpBx.setSizePolicy(sizePolicy)
        self.text1_grpBx.setTitle("")
        self.text1_grpBx.setObjectName("text1_grpBx")
        self.text1_grpBx_HLayout = QtWidgets.QHBoxLayout(self.text1_grpBx)
        self.text1_grpBx_HLayout.setContentsMargins(3, 2, 3, 2)
        self.text1_grpBx_HLayout.setObjectName("text1_grpBx_HLayout")
        self.text1_label = QtWidgets.QLabel(self.text1_grpBx)
        self.text1_label.setObjectName("text1_label")
        self.text1_grpBx_HLayout.addWidget(self.text1_label)
        self.text1_plainTextEdit = QtWidgets.QPlainTextEdit(self.text1_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text1_plainTextEdit.sizePolicy().hasHeightForWidth())
        self.text1_plainTextEdit.setSizePolicy(sizePolicy)
        self.text1_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.text1_plainTextEdit.setLineWidth(1)
        self.text1_plainTextEdit.setTabChangesFocus(True)
        self.text1_plainTextEdit.setObjectName("text1_plainTextEdit")
        self.text1_grpBx_HLayout.addWidget(self.text1_plainTextEdit)
        self.text1_comboBox = QtWidgets.QComboBox(self.text1_grpBx)
        self.text1_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.text1_comboBox.setMaxVisibleItems(6)
        self.text1_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.text1_comboBox.setObjectName("text1_comboBox")
        self.text1_grpBx_HLayout.addWidget(self.text1_comboBox)
        self.verticalLayout_3.addWidget(self.text1_grpBx)
        self.text2_grpBx = QtWidgets.QGroupBox(self.custom_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text2_grpBx.sizePolicy().hasHeightForWidth())
        self.text2_grpBx.setSizePolicy(sizePolicy)
        self.text2_grpBx.setTitle("")
        self.text2_grpBx.setObjectName("text2_grpBx")
        self.text2_grpBx_HLayout = QtWidgets.QHBoxLayout(self.text2_grpBx)
        self.text2_grpBx_HLayout.setContentsMargins(3, 2, 3, 2)
        self.text2_grpBx_HLayout.setObjectName("text2_grpBx_HLayout")
        self.text2_label = QtWidgets.QLabel(self.text2_grpBx)
        self.text2_label.setObjectName("text2_label")
        self.text2_grpBx_HLayout.addWidget(self.text2_label)
        self.text2_plainTextEdit = QtWidgets.QPlainTextEdit(self.text2_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text2_plainTextEdit.sizePolicy().hasHeightForWidth())
        self.text2_plainTextEdit.setSizePolicy(sizePolicy)
        self.text2_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.text2_plainTextEdit.setLineWidth(1)
        self.text2_plainTextEdit.setTabChangesFocus(True)
        self.text2_plainTextEdit.setObjectName("text2_plainTextEdit")
        self.text2_grpBx_HLayout.addWidget(self.text2_plainTextEdit)
        self.text2_comboBox = QtWidgets.QComboBox(self.text2_grpBx)
        self.text2_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.text2_comboBox.setMaxVisibleItems(6)
        self.text2_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.text2_comboBox.setObjectName("text2_comboBox")
        self.text2_grpBx_HLayout.addWidget(self.text2_comboBox)
        self.verticalLayout_3.addWidget(self.text2_grpBx)
        self.text3_grpBx = QtWidgets.QGroupBox(self.custom_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text3_grpBx.sizePolicy().hasHeightForWidth())
        self.text3_grpBx.setSizePolicy(sizePolicy)
        self.text3_grpBx.setTitle("")
        self.text3_grpBx.setObjectName("text3_grpBx")
        self.text3_grpBx_HLayout = QtWidgets.QHBoxLayout(self.text3_grpBx)
        self.text3_grpBx_HLayout.setContentsMargins(3, 2, 3, 2)
        self.text3_grpBx_HLayout.setObjectName("text3_grpBx_HLayout")
        self.text3_label = QtWidgets.QLabel(self.text3_grpBx)
        self.text3_label.setObjectName("text3_label")
        self.text3_grpBx_HLayout.addWidget(self.text3_label)
        self.text3_plainTextEdit = QtWidgets.QPlainTextEdit(self.text3_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text3_plainTextEdit.sizePolicy().hasHeightForWidth())
        self.text3_plainTextEdit.setSizePolicy(sizePolicy)
        self.text3_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.text3_plainTextEdit.setLineWidth(1)
        self.text3_plainTextEdit.setTabChangesFocus(True)
        self.text3_plainTextEdit.setObjectName("text3_plainTextEdit")
        self.text3_grpBx_HLayout.addWidget(self.text3_plainTextEdit)
        self.text3_comboBox = QtWidgets.QComboBox(self.text3_grpBx)
        self.text3_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.text3_comboBox.setMaxVisibleItems(6)
        self.text3_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.text3_comboBox.setObjectName("text3_comboBox")
        self.text3_grpBx_HLayout.addWidget(self.text3_comboBox)
        self.verticalLayout_3.addWidget(self.text3_grpBx)
        self.text4_grpBx = QtWidgets.QGroupBox(self.custom_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text4_grpBx.sizePolicy().hasHeightForWidth())
        self.text4_grpBx.setSizePolicy(sizePolicy)
        self.text4_grpBx.setTitle("")
        self.text4_grpBx.setObjectName("text4_grpBx")
        self.text3_grpBx_HLayout_2 = QtWidgets.QHBoxLayout(self.text4_grpBx)
        self.text3_grpBx_HLayout_2.setContentsMargins(3, 2, 3, 2)
        self.text3_grpBx_HLayout_2.setObjectName("text3_grpBx_HLayout_2")
        self.text4_label = QtWidgets.QLabel(self.text4_grpBx)
        self.text4_label.setObjectName("text4_label")
        self.text3_grpBx_HLayout_2.addWidget(self.text4_label)
        self.text4_plainTextEdit = QtWidgets.QPlainTextEdit(self.text4_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text4_plainTextEdit.sizePolicy().hasHeightForWidth())
        self.text4_plainTextEdit.setSizePolicy(sizePolicy)
        self.text4_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.text4_plainTextEdit.setLineWidth(1)
        self.text4_plainTextEdit.setTabChangesFocus(True)
        self.text4_plainTextEdit.setObjectName("text4_plainTextEdit")
        self.text3_grpBx_HLayout_2.addWidget(self.text4_plainTextEdit)
        self.text4_comboBox = QtWidgets.QComboBox(self.text4_grpBx)
        self.text4_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.text4_comboBox.setMaxVisibleItems(6)
        self.text4_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.text4_comboBox.setObjectName("text4_comboBox")
        self.text3_grpBx_HLayout_2.addWidget(self.text4_comboBox)
        self.verticalLayout_3.addWidget(self.text4_grpBx)
        self.basic_tab_VLayout.addWidget(self.custom_grpBx)
        self.mainTabWidget.addTab(self.basic_tab, "")
        self.zb_tab = QtWidgets.QWidget()
        self.zb_tab.setObjectName("zb_tab")
        self.zb_tab_HLayout = QtWidgets.QHBoxLayout(self.zb_tab)
        self.zb_tab_HLayout.setSpacing(6)
        self.zb_tab_HLayout.setContentsMargins(0, 0, 0, 0)
        self.zb_tab_HLayout.setObjectName("zb_tab_HLayout")
        self.zbScrollArea = QtWidgets.QScrollArea(self.zb_tab)
        self.zbScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.zbScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.zbScrollArea.setWidgetResizable(True)
        self.zbScrollArea.setObjectName("zbScrollArea")
        self.zbScrollAreaWdgContents = QtWidgets.QWidget()
        self.zbScrollAreaWdgContents.setGeometry(QtCore.QRect(0, 0, 334, 608))
        self.zbScrollAreaWdgContents.setObjectName("zbScrollAreaWdgContents")
        self.zb_scrollArea_VLayout = QtWidgets.QVBoxLayout(self.zbScrollAreaWdgContents)
        self.zb_scrollArea_VLayout.setSpacing(2)
        self.zb_scrollArea_VLayout.setContentsMargins(0, 9, 2, -1)
        self.zb_scrollArea_VLayout.setObjectName("zb_scrollArea_VLayout")
        self.zb_hiRes_grpBx = QtWidgets.QGroupBox(self.zbScrollAreaWdgContents)
        self.zb_hiRes_grpBx.setObjectName("zb_hiRes_grpBx")
        self.hiRes_grpBx_HLayout = QtWidgets.QHBoxLayout(self.zb_hiRes_grpBx)
        self.hiRes_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.hiRes_grpBx_HLayout.setObjectName("hiRes_grpBx_HLayout")
        self.zb_hiRes_listWdg = TTSListWidget(self.zb_hiRes_grpBx)
        self.zb_hiRes_listWdg.setAcceptDrops(True)
        self.zb_hiRes_listWdg.setObjectName("zb_hiRes_listWdg")
        self.hiRes_grpBx_HLayout.addWidget(self.zb_hiRes_listWdg)
        self.zb_hiRes_resetBtn = QtWidgets.QPushButton(self.zb_hiRes_grpBx)
        self.zb_hiRes_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.zb_hiRes_resetBtn.setFont(font)
        self.zb_hiRes_resetBtn.setStyleSheet("color: red")
        self.zb_hiRes_resetBtn.setObjectName("zb_hiRes_resetBtn")
        self.hiRes_grpBx_HLayout.addWidget(self.zb_hiRes_resetBtn)
        self.zb_scrollArea_VLayout.addWidget(self.zb_hiRes_grpBx)
        self.zb_loRes_grpBx = QtWidgets.QGroupBox(self.zbScrollAreaWdgContents)
        self.zb_loRes_grpBx.setObjectName("zb_loRes_grpBx")
        self.loRes_grpBx_HLayout = QtWidgets.QHBoxLayout(self.zb_loRes_grpBx)
        self.loRes_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.loRes_grpBx_HLayout.setObjectName("loRes_grpBx_HLayout")
        self.zb_loRes_listWdg = TTSListWidget(self.zb_loRes_grpBx)
        self.zb_loRes_listWdg.setAcceptDrops(True)
        self.zb_loRes_listWdg.setObjectName("zb_loRes_listWdg")
        self.loRes_grpBx_HLayout.addWidget(self.zb_loRes_listWdg)
        self.zb_loRes_resetBtn = QtWidgets.QPushButton(self.zb_loRes_grpBx)
        self.zb_loRes_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.zb_loRes_resetBtn.setFont(font)
        self.zb_loRes_resetBtn.setStyleSheet("color: red")
        self.zb_loRes_resetBtn.setObjectName("zb_loRes_resetBtn")
        self.loRes_grpBx_HLayout.addWidget(self.zb_loRes_resetBtn)
        self.zb_scrollArea_VLayout.addWidget(self.zb_loRes_grpBx)
        self.zbScrollArea.setWidget(self.zbScrollAreaWdgContents)
        self.zb_tab_HLayout.addWidget(self.zbScrollArea)
        self.mainTabWidget.addTab(self.zb_tab, "")
        self.sp_tab = QtWidgets.QWidget()
        self.sp_tab.setObjectName("sp_tab")
        self.sp_tab_HLayout = QtWidgets.QHBoxLayout(self.sp_tab)
        self.sp_tab_HLayout.setContentsMargins(0, 0, 0, 0)
        self.sp_tab_HLayout.setObjectName("sp_tab_HLayout")
        self.spScrollArea = QtWidgets.QScrollArea(self.sp_tab)
        self.spScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.spScrollArea.setWidgetResizable(True)
        self.spScrollArea.setObjectName("spScrollArea")
        self.spScrollAreaWdgContents = QtWidgets.QWidget()
        self.spScrollAreaWdgContents.setGeometry(QtCore.QRect(0, 0, 334, 772))
        self.spScrollAreaWdgContents.setObjectName("spScrollAreaWdgContents")
        self.sp_scrollArea_VLayout = QtWidgets.QVBoxLayout(self.spScrollAreaWdgContents)
        self.sp_scrollArea_VLayout.setSpacing(2)
        self.sp_scrollArea_VLayout.setContentsMargins(0, -1, 2, -1)
        self.sp_scrollArea_VLayout.setObjectName("sp_scrollArea_VLayout")
        self.sp_baseColor_grpBx = QtWidgets.QGroupBox(self.spScrollAreaWdgContents)
        self.sp_baseColor_grpBx.setStyleSheet("")
        self.sp_baseColor_grpBx.setObjectName("sp_baseColor_grpBx")
        self.baseColor_grpBox_HLayout = QtWidgets.QHBoxLayout(self.sp_baseColor_grpBx)
        self.baseColor_grpBox_HLayout.setContentsMargins(3, -1, 3, -1)
        self.baseColor_grpBox_HLayout.setObjectName("baseColor_grpBox_HLayout")
        self.sp_baseColor_listWdg = TTSListWidget(self.sp_baseColor_grpBx)
        self.sp_baseColor_listWdg.setBaseSize(QtCore.QSize(0, 0))
        self.sp_baseColor_listWdg.setAcceptDrops(True)
        self.sp_baseColor_listWdg.setObjectName("sp_baseColor_listWdg")
        self.baseColor_grpBox_HLayout.addWidget(self.sp_baseColor_listWdg)
        self.sp_baseColor_resetBtn = QtWidgets.QPushButton(self.sp_baseColor_grpBx)
        self.sp_baseColor_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.sp_baseColor_resetBtn.setFont(font)
        self.sp_baseColor_resetBtn.setStyleSheet("color: red")
        self.sp_baseColor_resetBtn.setObjectName("sp_baseColor_resetBtn")
        self.baseColor_grpBox_HLayout.addWidget(self.sp_baseColor_resetBtn)
        self.sp_scrollArea_VLayout.addWidget(self.sp_baseColor_grpBx)
        self.sp_metallic_grpBx = QtWidgets.QGroupBox(self.spScrollAreaWdgContents)
        self.sp_metallic_grpBx.setObjectName("sp_metallic_grpBx")
        self.metallic_grpBx_HLayout = QtWidgets.QHBoxLayout(self.sp_metallic_grpBx)
        self.metallic_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.metallic_grpBx_HLayout.setObjectName("metallic_grpBx_HLayout")
        self.sp_metallic_listWdg = TTSListWidget(self.sp_metallic_grpBx)
        self.sp_metallic_listWdg.setAcceptDrops(True)
        self.sp_metallic_listWdg.setObjectName("sp_metallic_listWdg")
        self.metallic_grpBx_HLayout.addWidget(self.sp_metallic_listWdg)
        self.sp_metallic_resetBtn = QtWidgets.QPushButton(self.sp_metallic_grpBx)
        self.sp_metallic_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.sp_metallic_resetBtn.setFont(font)
        self.sp_metallic_resetBtn.setStyleSheet("color: red")
        self.sp_metallic_resetBtn.setObjectName("sp_metallic_resetBtn")
        self.metallic_grpBx_HLayout.addWidget(self.sp_metallic_resetBtn)
        self.sp_scrollArea_VLayout.addWidget(self.sp_metallic_grpBx)
        self.sp_roughness_grpBx = QtWidgets.QGroupBox(self.spScrollAreaWdgContents)
        self.sp_roughness_grpBx.setObjectName("sp_roughness_grpBx")
        self.roughness_grpBx_HLayout = QtWidgets.QHBoxLayout(self.sp_roughness_grpBx)
        self.roughness_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.roughness_grpBx_HLayout.setObjectName("roughness_grpBx_HLayout")
        self.sp_roughness_listWdg = TTSListWidget(self.sp_roughness_grpBx)
        self.sp_roughness_listWdg.setAcceptDrops(True)
        self.sp_roughness_listWdg.setObjectName("sp_roughness_listWdg")
        self.roughness_grpBx_HLayout.addWidget(self.sp_roughness_listWdg)
        self.sp_roughness_resetBtn = QtWidgets.QPushButton(self.sp_roughness_grpBx)
        self.sp_roughness_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.sp_roughness_resetBtn.setFont(font)
        self.sp_roughness_resetBtn.setStyleSheet("color: red")
        self.sp_roughness_resetBtn.setObjectName("sp_roughness_resetBtn")
        self.roughness_grpBx_HLayout.addWidget(self.sp_roughness_resetBtn)
        self.sp_scrollArea_VLayout.addWidget(self.sp_roughness_grpBx)
        self.sp_normal_grpBx = QtWidgets.QGroupBox(self.spScrollAreaWdgContents)
        self.sp_normal_grpBx.setObjectName("sp_normal_grpBx")
        self.normal_grpBx_HLayout = QtWidgets.QHBoxLayout(self.sp_normal_grpBx)
        self.normal_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.normal_grpBx_HLayout.setObjectName("normal_grpBx_HLayout")
        self.sp_normal_listWdg = TTSListWidget(self.sp_normal_grpBx)
        self.sp_normal_listWdg.setAcceptDrops(True)
        self.sp_normal_listWdg.setObjectName("sp_normal_listWdg")
        self.normal_grpBx_HLayout.addWidget(self.sp_normal_listWdg)
        self.sp_normal_resetBtn = QtWidgets.QPushButton(self.sp_normal_grpBx)
        self.sp_normal_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.sp_normal_resetBtn.setFont(font)
        self.sp_normal_resetBtn.setStyleSheet("color: red")
        self.sp_normal_resetBtn.setObjectName("sp_normal_resetBtn")
        self.normal_grpBx_HLayout.addWidget(self.sp_normal_resetBtn)
        self.sp_scrollArea_VLayout.addWidget(self.sp_normal_grpBx)
        self.sp_height_grpBx = QtWidgets.QGroupBox(self.spScrollAreaWdgContents)
        self.sp_height_grpBx.setObjectName("sp_height_grpBx")
        self.height_grpBx_HLayout = QtWidgets.QHBoxLayout(self.sp_height_grpBx)
        self.height_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.height_grpBx_HLayout.setObjectName("height_grpBx_HLayout")
        self.sp_height_listWdg = TTSListWidget(self.sp_height_grpBx)
        self.sp_height_listWdg.setAcceptDrops(True)
        self.sp_height_listWdg.setObjectName("sp_height_listWdg")
        self.height_grpBx_HLayout.addWidget(self.sp_height_listWdg)
        self.sp_height_resetBtn = QtWidgets.QPushButton(self.sp_height_grpBx)
        self.sp_height_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.sp_height_resetBtn.setFont(font)
        self.sp_height_resetBtn.setStyleSheet("color: red")
        self.sp_height_resetBtn.setObjectName("sp_height_resetBtn")
        self.height_grpBx_HLayout.addWidget(self.sp_height_resetBtn)
        self.sp_scrollArea_VLayout.addWidget(self.sp_height_grpBx)
        self.sp_ao_grpBx = QtWidgets.QGroupBox(self.spScrollAreaWdgContents)
        self.sp_ao_grpBx.setObjectName("sp_ao_grpBx")
        self.ao_grpBx_HLayout = QtWidgets.QHBoxLayout(self.sp_ao_grpBx)
        self.ao_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.ao_grpBx_HLayout.setObjectName("ao_grpBx_HLayout")
        self.sp_ao_listWdg = TTSListWidget(self.sp_ao_grpBx)
        self.sp_ao_listWdg.setAcceptDrops(True)
        self.sp_ao_listWdg.setObjectName("sp_ao_listWdg")
        self.ao_grpBx_HLayout.addWidget(self.sp_ao_listWdg)
        self.sp_ao_resetBtn = QtWidgets.QPushButton(self.sp_ao_grpBx)
        self.sp_ao_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.sp_ao_resetBtn.setFont(font)
        self.sp_ao_resetBtn.setStyleSheet("color: red")
        self.sp_ao_resetBtn.setObjectName("sp_ao_resetBtn")
        self.ao_grpBx_HLayout.addWidget(self.sp_ao_resetBtn)
        self.sp_scrollArea_VLayout.addWidget(self.sp_ao_grpBx)
        self.sp_emissive_grpBx = QtWidgets.QGroupBox(self.spScrollAreaWdgContents)
        self.sp_emissive_grpBx.setObjectName("sp_emissive_grpBx")
        self.emissive_grpBx_HLayout = QtWidgets.QHBoxLayout(self.sp_emissive_grpBx)
        self.emissive_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.emissive_grpBx_HLayout.setObjectName("emissive_grpBx_HLayout")
        self.sp_emissive_listWdg = TTSListWidget(self.sp_emissive_grpBx)
        self.sp_emissive_listWdg.setAcceptDrops(True)
        self.sp_emissive_listWdg.setObjectName("sp_emissive_listWdg")
        self.emissive_grpBx_HLayout.addWidget(self.sp_emissive_listWdg)
        self.sp_emissive_resetBtn = QtWidgets.QPushButton(self.sp_emissive_grpBx)
        self.sp_emissive_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.sp_emissive_resetBtn.setFont(font)
        self.sp_emissive_resetBtn.setStyleSheet("color: red")
        self.sp_emissive_resetBtn.setObjectName("sp_emissive_resetBtn")
        self.emissive_grpBx_HLayout.addWidget(self.sp_emissive_resetBtn)
        self.sp_scrollArea_VLayout.addWidget(self.sp_emissive_grpBx)
        self.spScrollArea.setWidget(self.spScrollAreaWdgContents)
        self.sp_tab_HLayout.addWidget(self.spScrollArea)
        self.mainTabWidget.addTab(self.sp_tab, "")
        self.before_vs_after_tab = QtWidgets.QWidget()
        self.before_vs_after_tab.setObjectName("before_vs_after_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.before_vs_after_tab)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bvsa_btn_grpBx = QtWidgets.QGroupBox(self.before_vs_after_tab)
        self.bvsa_btn_grpBx.setTitle("")
        self.bvsa_btn_grpBx.setObjectName("bvsa_btn_grpBx")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.bvsa_btn_grpBx)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.bvsa_caption_grpBx = QtWidgets.QGroupBox(self.bvsa_btn_grpBx)
        self.bvsa_caption_grpBx.setObjectName("bvsa_caption_grpBx")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.bvsa_caption_grpBx)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.bvsa_caption_HLayout = QtWidgets.QHBoxLayout()
        self.bvsa_caption_HLayout.setObjectName("bvsa_caption_HLayout")
        self.bvsa_caption_banner_checkBox = QtWidgets.QCheckBox(self.bvsa_caption_grpBx)
        self.bvsa_caption_banner_checkBox.setChecked(True)
        self.bvsa_caption_banner_checkBox.setObjectName("bvsa_caption_banner_checkBox")
        self.bvsa_caption_HLayout.addWidget(self.bvsa_caption_banner_checkBox)
        self.bvsa_caption_label = QtWidgets.QLabel(self.bvsa_caption_grpBx)
        self.bvsa_caption_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bvsa_caption_label.setObjectName("bvsa_caption_label")
        self.bvsa_caption_HLayout.addWidget(self.bvsa_caption_label)
        self.bvsa_caption_align_comboBox = QtWidgets.QComboBox(self.bvsa_caption_grpBx)
        self.bvsa_caption_align_comboBox.setMaximumSize(QtCore.QSize(75, 16777215))
        self.bvsa_caption_align_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bvsa_caption_align_comboBox.setObjectName("bvsa_caption_align_comboBox")
        self.bvsa_caption_align_comboBox.addItem("")
        self.bvsa_caption_align_comboBox.addItem("")
        self.bvsa_caption_HLayout.addWidget(self.bvsa_caption_align_comboBox)
        self.verticalLayout_8.addLayout(self.bvsa_caption_HLayout)
        self.verticalLayout_7.addWidget(self.bvsa_caption_grpBx)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bvsa_clearAll_btn = QtWidgets.QPushButton(self.bvsa_btn_grpBx)
        self.bvsa_clearAll_btn.setObjectName("bvsa_clearAll_btn")
        self.horizontalLayout.addWidget(self.bvsa_clearAll_btn)
        self.bvsa_execute_btn = QtWidgets.QPushButton(self.bvsa_btn_grpBx)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bvsa_execute_btn.setFont(font)
        self.bvsa_execute_btn.setStyleSheet("background-color: rgb(189, 28, 70); color: white")
        self.bvsa_execute_btn.setObjectName("bvsa_execute_btn")
        self.horizontalLayout.addWidget(self.bvsa_execute_btn)
        self.bvsa_showResult_btn = QtWidgets.QPushButton(self.bvsa_btn_grpBx)
        self.bvsa_showResult_btn.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bvsa_showResult_btn.setFont(font)
        self.bvsa_showResult_btn.setObjectName("bvsa_showResult_btn")
        self.horizontalLayout.addWidget(self.bvsa_showResult_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.bvsa_btn_grpBx)
        self.before_grpBx = QtWidgets.QGroupBox(self.before_vs_after_tab)
        self.before_grpBx.setTitle("")
        self.before_grpBx.setObjectName("before_grpBx")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.before_grpBx)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.before_graphicsView = TTSGraphicsView(self.before_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.before_graphicsView.sizePolicy().hasHeightForWidth())
        self.before_graphicsView.setSizePolicy(sizePolicy)
        self.before_graphicsView.setMinimumSize(QtCore.QSize(250, 250))
        self.before_graphicsView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.before_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.before_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.before_graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.before_graphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.before_graphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.before_graphicsView.setObjectName("before_graphicsView")
        self.horizontalLayout_2.addWidget(self.before_graphicsView)
        self.before_controls_grpBx = QtWidgets.QGroupBox(self.before_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.before_controls_grpBx.sizePolicy().hasHeightForWidth())
        self.before_controls_grpBx.setSizePolicy(sizePolicy)
        self.before_controls_grpBx.setMaximumSize(QtCore.QSize(150, 16777215))
        self.before_controls_grpBx.setAlignment(QtCore.Qt.AlignCenter)
        self.before_controls_grpBx.setObjectName("before_controls_grpBx")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.before_controls_grpBx)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bvsa_before_screenshot_HLayout = QtWidgets.QHBoxLayout()
        self.bvsa_before_screenshot_HLayout.setObjectName("bvsa_before_screenshot_HLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bvsa_before_screenshot_HLayout.addItem(spacerItem)
        self.bvsa_before_screenshot_btn = QtWidgets.QPushButton(self.before_controls_grpBx)
        self.bvsa_before_screenshot_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.bvsa_before_screenshot_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.bvsa_before_screenshot_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bvsa_before_screenshot_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Greenshot_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bvsa_before_screenshot_btn.setIcon(icon)
        self.bvsa_before_screenshot_btn.setIconSize(QtCore.QSize(24, 24))
        self.bvsa_before_screenshot_btn.setObjectName("bvsa_before_screenshot_btn")
        self.bvsa_before_screenshot_HLayout.addWidget(self.bvsa_before_screenshot_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bvsa_before_screenshot_HLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.bvsa_before_screenshot_HLayout)
        self.bvsa_before_load_img_HLayout = QtWidgets.QHBoxLayout()
        self.bvsa_before_load_img_HLayout.setObjectName("bvsa_before_load_img_HLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bvsa_before_load_img_HLayout.addItem(spacerItem2)
        self.bvsa_before_load_img_btn = QtWidgets.QPushButton(self.before_controls_grpBx)
        self.bvsa_before_load_img_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.bvsa_before_load_img_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.bvsa_before_load_img_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/outline_autorenew_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bvsa_before_load_img_btn.setIcon(icon1)
        self.bvsa_before_load_img_btn.setIconSize(QtCore.QSize(18, 18))
        self.bvsa_before_load_img_btn.setObjectName("bvsa_before_load_img_btn")
        self.bvsa_before_load_img_HLayout.addWidget(self.bvsa_before_load_img_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bvsa_before_load_img_HLayout.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.bvsa_before_load_img_HLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.bvsa_before_plainTextEdit = QtWidgets.QPlainTextEdit(self.before_controls_grpBx)
        self.bvsa_before_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.bvsa_before_plainTextEdit.setObjectName("bvsa_before_plainTextEdit")
        self.verticalLayout_5.addWidget(self.bvsa_before_plainTextEdit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_2.addWidget(self.before_controls_grpBx)
        self.verticalLayout_2.addWidget(self.before_grpBx)
        self.after_grpBx = QtWidgets.QGroupBox(self.before_vs_after_tab)
        self.after_grpBx.setTitle("")
        self.after_grpBx.setObjectName("after_grpBx")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.after_grpBx)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.after_graphicsView = TTSGraphicsView(self.after_grpBx)
        self.after_graphicsView.setMinimumSize(QtCore.QSize(250, 250))
        self.after_graphicsView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.after_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.after_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.after_graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.after_graphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.after_graphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.after_graphicsView.setObjectName("after_graphicsView")
        self.horizontalLayout_3.addWidget(self.after_graphicsView)
        self.after_controls_grpBx = QtWidgets.QGroupBox(self.after_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.after_controls_grpBx.sizePolicy().hasHeightForWidth())
        self.after_controls_grpBx.setSizePolicy(sizePolicy)
        self.after_controls_grpBx.setMaximumSize(QtCore.QSize(150, 16777215))
        self.after_controls_grpBx.setAlignment(QtCore.Qt.AlignCenter)
        self.after_controls_grpBx.setObjectName("after_controls_grpBx")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.after_controls_grpBx)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bvsa_after_screenshot_HLayout = QtWidgets.QHBoxLayout()
        self.bvsa_after_screenshot_HLayout.setObjectName("bvsa_after_screenshot_HLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bvsa_after_screenshot_HLayout.addItem(spacerItem6)
        self.bvsa_after_screenshot_btn = QtWidgets.QPushButton(self.after_controls_grpBx)
        self.bvsa_after_screenshot_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.bvsa_after_screenshot_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.bvsa_after_screenshot_btn.setText("")
        self.bvsa_after_screenshot_btn.setIcon(icon)
        self.bvsa_after_screenshot_btn.setIconSize(QtCore.QSize(24, 24))
        self.bvsa_after_screenshot_btn.setObjectName("bvsa_after_screenshot_btn")
        self.bvsa_after_screenshot_HLayout.addWidget(self.bvsa_after_screenshot_btn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bvsa_after_screenshot_HLayout.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.bvsa_after_screenshot_HLayout)
        self.bvsa_after_load_img_HLayout = QtWidgets.QHBoxLayout()
        self.bvsa_after_load_img_HLayout.setObjectName("bvsa_after_load_img_HLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bvsa_after_load_img_HLayout.addItem(spacerItem8)
        self.bvsa_after_load_img_btn = QtWidgets.QPushButton(self.after_controls_grpBx)
        self.bvsa_after_load_img_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.bvsa_after_load_img_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.bvsa_after_load_img_btn.setText("")
        self.bvsa_after_load_img_btn.setIcon(icon1)
        self.bvsa_after_load_img_btn.setIconSize(QtCore.QSize(18, 18))
        self.bvsa_after_load_img_btn.setObjectName("bvsa_after_load_img_btn")
        self.bvsa_after_load_img_HLayout.addWidget(self.bvsa_after_load_img_btn)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bvsa_after_load_img_HLayout.addItem(spacerItem9)
        self.verticalLayout_6.addLayout(self.bvsa_after_load_img_HLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.bvsa_after_plainTextEdit = QtWidgets.QPlainTextEdit(self.after_controls_grpBx)
        self.bvsa_after_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.bvsa_after_plainTextEdit.setObjectName("bvsa_after_plainTextEdit")
        self.verticalLayout_6.addWidget(self.bvsa_after_plainTextEdit)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem11)
        self.horizontalLayout_3.addWidget(self.after_controls_grpBx)
        self.verticalLayout_2.addWidget(self.after_grpBx)
        self.mainTabWidget.addTab(self.before_vs_after_tab, "")
        self.video_tab = QtWidgets.QWidget()
        self.video_tab.setObjectName("video_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.video_tab)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.clamp_vid_size_btn_grpBx = QtWidgets.QGroupBox(self.video_tab)
        self.clamp_vid_size_btn_grpBx.setTitle("")
        self.clamp_vid_size_btn_grpBx.setObjectName("clamp_vid_size_btn_grpBx")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.clamp_vid_size_btn_grpBx)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clamp_vid_size_spinBox_label = QtWidgets.QLabel(self.clamp_vid_size_btn_grpBx)
        self.clamp_vid_size_spinBox_label.setMaximumSize(QtCore.QSize(22, 16777215))
        self.clamp_vid_size_spinBox_label.setObjectName("clamp_vid_size_spinBox_label")
        self.horizontalLayout_4.addWidget(self.clamp_vid_size_spinBox_label)
        self.clamp_vid_size_spinBox = QtWidgets.QSpinBox(self.clamp_vid_size_btn_grpBx)
        self.clamp_vid_size_spinBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.clamp_vid_size_spinBox.setMinimum(1)
        self.clamp_vid_size_spinBox.setMaximum(100)
        self.clamp_vid_size_spinBox.setProperty("value", 10)
        self.clamp_vid_size_spinBox.setObjectName("clamp_vid_size_spinBox")
        self.horizontalLayout_4.addWidget(self.clamp_vid_size_spinBox)
        self.clamp_vid_size_execute_btn = QtWidgets.QPushButton(self.clamp_vid_size_btn_grpBx)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clamp_vid_size_execute_btn.setFont(font)
        self.clamp_vid_size_execute_btn.setStyleSheet("background-color: rgb(66, 227, 185);")
        self.clamp_vid_size_execute_btn.setObjectName("clamp_vid_size_execute_btn")
        self.horizontalLayout_4.addWidget(self.clamp_vid_size_execute_btn)
        self.verticalLayout_4.addWidget(self.clamp_vid_size_btn_grpBx)
        self.clamp_vid_size_grpBx = QtWidgets.QGroupBox(self.video_tab)
        self.clamp_vid_size_grpBx.setObjectName("clamp_vid_size_grpBx")
        self.hiRes_grpBx_HLayout_2 = QtWidgets.QHBoxLayout(self.clamp_vid_size_grpBx)
        self.hiRes_grpBx_HLayout_2.setSpacing(12)
        self.hiRes_grpBx_HLayout_2.setContentsMargins(9, -1, 9, -1)
        self.hiRes_grpBx_HLayout_2.setObjectName("hiRes_grpBx_HLayout_2")
        self.clamp_vid_size_listWdg = TTSListWidget_Video(self.clamp_vid_size_grpBx)
        self.clamp_vid_size_listWdg.setAcceptDrops(True)
        self.clamp_vid_size_listWdg.setObjectName("clamp_vid_size_listWdg")
        self.hiRes_grpBx_HLayout_2.addWidget(self.clamp_vid_size_listWdg)
        self.clamp_vid_size_resetBtn = QtWidgets.QPushButton(self.clamp_vid_size_grpBx)
        self.clamp_vid_size_resetBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.clamp_vid_size_resetBtn.setFont(font)
        self.clamp_vid_size_resetBtn.setStyleSheet("color: red")
        self.clamp_vid_size_resetBtn.setObjectName("clamp_vid_size_resetBtn")
        self.hiRes_grpBx_HLayout_2.addWidget(self.clamp_vid_size_resetBtn)
        self.verticalLayout_4.addWidget(self.clamp_vid_size_grpBx)
        self.mainTabWidget.addTab(self.video_tab, "")
        self.config_tab = QtWidgets.QWidget()
        self.config_tab.setEnabled(True)
        self.config_tab.setObjectName("config_tab")
        self.config_tab_VLayout = QtWidgets.QVBoxLayout(self.config_tab)
        self.config_tab_VLayout.setContentsMargins(3, -1, 3, -1)
        self.config_tab_VLayout.setObjectName("config_tab_VLayout")
        self.theme_grpBx = QtWidgets.QGroupBox(self.config_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theme_grpBx.sizePolicy().hasHeightForWidth())
        self.theme_grpBx.setSizePolicy(sizePolicy)
        self.theme_grpBx.setMinimumSize(QtCore.QSize(0, 60))
        self.theme_grpBx.setObjectName("theme_grpBx")
        self.theme_grpBx_HLayout = QtWidgets.QHBoxLayout(self.theme_grpBx)
        self.theme_grpBx_HLayout.setContentsMargins(3, -1, 3, -1)
        self.theme_grpBx_HLayout.setObjectName("theme_grpBx_HLayout")
        self.theme_comboBox = QtWidgets.QComboBox(self.theme_grpBx)
        self.theme_comboBox.setObjectName("theme_comboBox")
        self.theme_comboBox.addItem("")
        self.theme_comboBox.addItem("")
        self.theme_comboBox.addItem("")
        self.theme_comboBox.addItem("")
        self.theme_comboBox.addItem("")
        self.theme_grpBx_HLayout.addWidget(self.theme_comboBox)
        self.config_tab_VLayout.addWidget(self.theme_grpBx)
        self.textSettings_grpBx = QtWidgets.QGroupBox(self.config_tab)
        self.textSettings_grpBx.setObjectName("textSettings_grpBx")
        self.formLayout = QtWidgets.QFormLayout(self.textSettings_grpBx)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.marginSize_label = QtWidgets.QLabel(self.textSettings_grpBx)
        self.marginSize_label.setObjectName("marginSize_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.marginSize_label)
        self.marginSize_spinBox = QtWidgets.QSpinBox(self.textSettings_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.marginSize_spinBox.sizePolicy().hasHeightForWidth())
        self.marginSize_spinBox.setSizePolicy(sizePolicy)
        self.marginSize_spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.marginSize_spinBox.setMinimum(10)
        self.marginSize_spinBox.setMaximum(499)
        self.marginSize_spinBox.setProperty("value", 40)
        self.marginSize_spinBox.setObjectName("marginSize_spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.marginSize_spinBox)
        self.customTxtFontSize_label = QtWidgets.QLabel(self.textSettings_grpBx)
        self.customTxtFontSize_label.setObjectName("customTxtFontSize_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.customTxtFontSize_label)
        self.customTxtFontSize_spinBox = QtWidgets.QSpinBox(self.textSettings_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customTxtFontSize_spinBox.sizePolicy().hasHeightForWidth())
        self.customTxtFontSize_spinBox.setSizePolicy(sizePolicy)
        self.customTxtFontSize_spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.customTxtFontSize_spinBox.setMinimum(6)
        self.customTxtFontSize_spinBox.setMaximum(299)
        self.customTxtFontSize_spinBox.setProperty("value", 35)
        self.customTxtFontSize_spinBox.setObjectName("customTxtFontSize_spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.customTxtFontSize_spinBox)
        self.autoDateFontSize_label = QtWidgets.QLabel(self.textSettings_grpBx)
        self.autoDateFontSize_label.setObjectName("autoDateFontSize_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.autoDateFontSize_label)
        self.autoDateFrontSize_spinBox = QtWidgets.QSpinBox(self.textSettings_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoDateFrontSize_spinBox.sizePolicy().hasHeightForWidth())
        self.autoDateFrontSize_spinBox.setSizePolicy(sizePolicy)
        self.autoDateFrontSize_spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.autoDateFrontSize_spinBox.setMinimum(6)
        self.autoDateFrontSize_spinBox.setMaximum(299)
        self.autoDateFrontSize_spinBox.setProperty("value", 30)
        self.autoDateFrontSize_spinBox.setObjectName("autoDateFrontSize_spinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.autoDateFrontSize_spinBox)
        self.strokeWidth_label = QtWidgets.QLabel(self.textSettings_grpBx)
        self.strokeWidth_label.setObjectName("strokeWidth_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.strokeWidth_label)
        self.strokeWidth_spinBox = QtWidgets.QSpinBox(self.textSettings_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strokeWidth_spinBox.sizePolicy().hasHeightForWidth())
        self.strokeWidth_spinBox.setSizePolicy(sizePolicy)
        self.strokeWidth_spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.strokeWidth_spinBox.setMaximum(10)
        self.strokeWidth_spinBox.setProperty("value", 2)
        self.strokeWidth_spinBox.setObjectName("strokeWidth_spinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.strokeWidth_spinBox)
        self.config_tab_VLayout.addWidget(self.textSettings_grpBx)
        self.imgSettings_grpBx = QtWidgets.QGroupBox(self.config_tab)
        self.imgSettings_grpBx.setObjectName("imgSettings_grpBx")
        self.formLayout_2 = QtWidgets.QFormLayout(self.imgSettings_grpBx)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.companyLogoSetting_label = QtWidgets.QLabel(self.imgSettings_grpBx)
        self.companyLogoSetting_label.setObjectName("companyLogoSetting_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.companyLogoSetting_label)
        self.companyLogoSetting_spinBox = QtWidgets.QSpinBox(self.imgSettings_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.companyLogoSetting_spinBox.sizePolicy().hasHeightForWidth())
        self.companyLogoSetting_spinBox.setSizePolicy(sizePolicy)
        self.companyLogoSetting_spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.companyLogoSetting_spinBox.setMinimum(5)
        self.companyLogoSetting_spinBox.setMaximum(30)
        self.companyLogoSetting_spinBox.setProperty("value", 15)
        self.companyLogoSetting_spinBox.setObjectName("companyLogoSetting_spinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.companyLogoSetting_spinBox)
        self.bvsa_bckgrd_color_label = QtWidgets.QLabel(self.imgSettings_grpBx)
        self.bvsa_bckgrd_color_label.setObjectName("bvsa_bckgrd_color_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bvsa_bckgrd_color_label)
        self.bvsa_bckgrd_color_btn = QtWidgets.QPushButton(self.imgSettings_grpBx)
        self.bvsa_bckgrd_color_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bvsa_bckgrd_color_btn.setStyleSheet("")
        self.bvsa_bckgrd_color_btn.setText("")
        self.bvsa_bckgrd_color_btn.setObjectName("bvsa_bckgrd_color_btn")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bvsa_bckgrd_color_btn)
        self.config_tab_VLayout.addWidget(self.imgSettings_grpBx)
        self.configPlainTextEdit = QtWidgets.QPlainTextEdit(self.config_tab)
        self.configPlainTextEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.configPlainTextEdit.setSizePolicy(sizePolicy)
        self.configPlainTextEdit.setReadOnly(True)
        self.configPlainTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.configPlainTextEdit.setObjectName("configPlainTextEdit")
        self.config_tab_VLayout.addWidget(self.configPlainTextEdit)
        self.mainTabWidget.addTab(self.config_tab, "")
        self.main_VLayout.addWidget(self.mainTabWidget)
        self.execute_grpBx = QtWidgets.QGroupBox(self.centralWdg)
        self.execute_grpBx.setTitle("")
        self.execute_grpBx.setObjectName("execute_grpBx")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.execute_grpBx)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stampOptions_gridLayout = QtWidgets.QGridLayout()
        self.stampOptions_gridLayout.setObjectName("stampOptions_gridLayout")
        self.outputAsJPG_checkBox = QtWidgets.QCheckBox(self.execute_grpBx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputAsJPG_checkBox.sizePolicy().hasHeightForWidth())
        self.outputAsJPG_checkBox.setSizePolicy(sizePolicy)
        self.outputAsJPG_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.outputAsJPG_checkBox.setChecked(True)
        self.outputAsJPG_checkBox.setObjectName("outputAsJPG_checkBox")
        self.stampOptions_gridLayout.addWidget(self.outputAsJPG_checkBox, 3, 1, 1, 1)
        self.srcOverwrite_checkBox = QtWidgets.QCheckBox(self.execute_grpBx)
        self.srcOverwrite_checkBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcOverwrite_checkBox.sizePolicy().hasHeightForWidth())
        self.srcOverwrite_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.srcOverwrite_checkBox.setFont(font)
        self.srcOverwrite_checkBox.setChecked(True)
        self.srcOverwrite_checkBox.setObjectName("srcOverwrite_checkBox")
        self.stampOptions_gridLayout.addWidget(self.srcOverwrite_checkBox, 3, 0, 1, 1)
        self.autoDate_checkBox = QtWidgets.QCheckBox(self.execute_grpBx)
        self.autoDate_checkBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoDate_checkBox.sizePolicy().hasHeightForWidth())
        self.autoDate_checkBox.setSizePolicy(sizePolicy)
        self.autoDate_checkBox.setChecked(True)
        self.autoDate_checkBox.setObjectName("autoDate_checkBox")
        self.stampOptions_gridLayout.addWidget(self.autoDate_checkBox, 1, 0, 1, 1)
        self.unifyOutputs_checkBox = QtWidgets.QCheckBox(self.execute_grpBx)
        self.unifyOutputs_checkBox.setObjectName("unifyOutputs_checkBox")
        self.stampOptions_gridLayout.addWidget(self.unifyOutputs_checkBox, 2, 0, 1, 1)
        self.companyLogo_checkBox = QtWidgets.QCheckBox(self.execute_grpBx)
        self.companyLogo_checkBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.companyLogo_checkBox.sizePolicy().hasHeightForWidth())
        self.companyLogo_checkBox.setSizePolicy(sizePolicy)
        self.companyLogo_checkBox.setChecked(False)
        self.companyLogo_checkBox.setTristate(False)
        self.companyLogo_checkBox.setObjectName("companyLogo_checkBox")
        self.stampOptions_gridLayout.addWidget(self.companyLogo_checkBox, 1, 1, 1, 1)
        self.unifyOutputs_HLayout = QtWidgets.QHBoxLayout()
        self.unifyOutputs_HLayout.setObjectName("unifyOutputs_HLayout")
        self.unifyOutputs_width_spinBox = QtWidgets.QSpinBox(self.execute_grpBx)
        self.unifyOutputs_width_spinBox.setEnabled(False)
        self.unifyOutputs_width_spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.unifyOutputs_width_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.unifyOutputs_width_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.unifyOutputs_width_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.unifyOutputs_width_spinBox.setMinimum(1)
        self.unifyOutputs_width_spinBox.setMaximum(8192)
        self.unifyOutputs_width_spinBox.setProperty("value", 1920)
        self.unifyOutputs_width_spinBox.setObjectName("unifyOutputs_width_spinBox")
        self.unifyOutputs_HLayout.addWidget(self.unifyOutputs_width_spinBox)
        self.unifyOutputs_x_label = QtWidgets.QLabel(self.execute_grpBx)
        self.unifyOutputs_x_label.setEnabled(False)
        self.unifyOutputs_x_label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.unifyOutputs_x_label.setAlignment(QtCore.Qt.AlignCenter)
        self.unifyOutputs_x_label.setObjectName("unifyOutputs_x_label")
        self.unifyOutputs_HLayout.addWidget(self.unifyOutputs_x_label)
        self.unifyOutputs_height_spinBox = QtWidgets.QSpinBox(self.execute_grpBx)
        self.unifyOutputs_height_spinBox.setEnabled(False)
        self.unifyOutputs_height_spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.unifyOutputs_height_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.unifyOutputs_height_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.unifyOutputs_height_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.unifyOutputs_height_spinBox.setMinimum(1)
        self.unifyOutputs_height_spinBox.setMaximum(8192)
        self.unifyOutputs_height_spinBox.setProperty("value", 1080)
        self.unifyOutputs_height_spinBox.setObjectName("unifyOutputs_height_spinBox")
        self.unifyOutputs_HLayout.addWidget(self.unifyOutputs_height_spinBox)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.unifyOutputs_HLayout.addItem(spacerItem12)
        self.stampOptions_gridLayout.addLayout(self.unifyOutputs_HLayout, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.stampOptions_gridLayout)
        self.execute_HLayout = QtWidgets.QHBoxLayout()
        self.execute_HLayout.setObjectName("execute_HLayout")
        self.browseOutput_btn = QtWidgets.QPushButton(self.execute_grpBx)
        self.browseOutput_btn.setEnabled(False)
        self.browseOutput_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.browseOutput_btn.setFont(font)
        self.browseOutput_btn.setStyleSheet("")
        self.browseOutput_btn.setObjectName("browseOutput_btn")
        self.execute_HLayout.addWidget(self.browseOutput_btn)
        self.stampAll_btn = QtWidgets.QPushButton(self.execute_grpBx)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.stampAll_btn.setFont(font)
        self.stampAll_btn.setObjectName("stampAll_btn")
        self.execute_HLayout.addWidget(self.stampAll_btn)
        self.verticalLayout.addLayout(self.execute_HLayout)
        self.performStamp_progressBar = QtWidgets.QProgressBar(self.execute_grpBx)
        self.performStamp_progressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.performStamp_progressBar.sizePolicy().hasHeightForWidth())
        self.performStamp_progressBar.setSizePolicy(sizePolicy)
        self.performStamp_progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.performStamp_progressBar.setProperty("value", 0)
        self.performStamp_progressBar.setObjectName("performStamp_progressBar")
        self.verticalLayout.addWidget(self.performStamp_progressBar)
        self.main_VLayout.addWidget(self.execute_grpBx)
        ttStamperWindow.setCentralWidget(self.centralWdg)

        self.retranslateUi(ttStamperWindow)
        self.mainTabWidget.setCurrentIndex(0)
        self.bvsa_caption_align_comboBox.setCurrentIndex(1)
        self.theme_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ttStamperWindow)

    def retranslateUi(self, ttStamperWindow):
        ttStamperWindow.setWindowTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Turntable Stamper", None, -1))
        self.basicTemplate_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Templates", None, -1))
        self.basicTemplate_removeBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "-", None, -1))
        self.basicSrc_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Sources", None, -1))
        self.basicSrc_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.custom_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Custom", None, -1))
        self.text1_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Text 1:", None, -1))
        self.text2_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Text 2:", None, -1))
        self.text3_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Text 3:", None, -1))
        self.text4_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Text 4:", None, -1))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.basic_tab), QtWidgets.QApplication.translate("ttStamperWindow", "Basic", None, -1))
        self.zb_hiRes_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Hi-Res", None, -1))
        self.zb_hiRes_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.zb_loRes_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Lo-Res", None, -1))
        self.zb_loRes_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.zb_tab), QtWidgets.QApplication.translate("ttStamperWindow", "ZBrush", None, -1))
        self.sp_baseColor_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Base Color", None, -1))
        self.sp_baseColor_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.sp_metallic_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Metallic", None, -1))
        self.sp_metallic_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.sp_roughness_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Roughness", None, -1))
        self.sp_roughness_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.sp_normal_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Normal", None, -1))
        self.sp_normal_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.sp_height_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Height", None, -1))
        self.sp_height_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.sp_ao_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "AO", None, -1))
        self.sp_ao_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.sp_emissive_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Emissive", None, -1))
        self.sp_emissive_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.sp_tab), QtWidgets.QApplication.translate("ttStamperWindow", "Substance", None, -1))
        self.bvsa_caption_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "CAPTIONS", None, -1))
        self.bvsa_caption_banner_checkBox.setText(QtWidgets.QApplication.translate("ttStamperWindow", "in Top Banner", None, -1))
        self.bvsa_caption_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Align", None, -1))
        self.bvsa_caption_align_comboBox.setItemText(0, QtWidgets.QApplication.translate("ttStamperWindow", "left", None, -1))
        self.bvsa_caption_align_comboBox.setItemText(1, QtWidgets.QApplication.translate("ttStamperWindow", "center", None, -1))
        self.bvsa_clearAll_btn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Clear All", None, -1))
        self.bvsa_execute_btn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "CONCAT.", None, -1))
        self.bvsa_showResult_btn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Show Result", None, -1))
        self.before_controls_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "LEFT IMAGE", None, -1))
        self.bvsa_before_plainTextEdit.setPlainText(QtWidgets.QApplication.translate("ttStamperWindow", "before", None, -1))
        self.after_controls_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "RIGHT IMAGE", None, -1))
        self.bvsa_after_plainTextEdit.setPlainText(QtWidgets.QApplication.translate("ttStamperWindow", "after", None, -1))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.before_vs_after_tab), QtWidgets.QApplication.translate("ttStamperWindow", "Before After", None, -1))
        self.clamp_vid_size_spinBox_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Max:", None, -1))
        self.clamp_vid_size_spinBox.setSuffix(QtWidgets.QApplication.translate("ttStamperWindow", " MB", None, -1))
        self.clamp_vid_size_execute_btn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "CLAMP FILE SIZE", None, -1))
        self.clamp_vid_size_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "Videos", None, -1))
        self.clamp_vid_size_resetBtn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "X", None, -1))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.video_tab), QtWidgets.QApplication.translate("ttStamperWindow", "Videos", None, -1))
        self.theme_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "THEMES", None, -1))
        self.theme_comboBox.setItemText(0, QtWidgets.QApplication.translate("ttStamperWindow", "Default", None, -1))
        self.theme_comboBox.setItemText(1, QtWidgets.QApplication.translate("ttStamperWindow", "Dark", None, -1))
        self.theme_comboBox.setItemText(2, QtWidgets.QApplication.translate("ttStamperWindow", "Aqua", None, -1))
        self.theme_comboBox.setItemText(3, QtWidgets.QApplication.translate("ttStamperWindow", "Console", None, -1))
        self.theme_comboBox.setItemText(4, QtWidgets.QApplication.translate("ttStamperWindow", "Ubuntu", None, -1))
        self.textSettings_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "*** TEXT SETTINGS ***", None, -1))
        self.marginSize_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Margin (x=y)", None, -1))
        self.customTxtFontSize_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Font Size of All Custom Text   ", None, -1))
        self.autoDateFontSize_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Font Size of Auto Date", None, -1))
        self.strokeWidth_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Stroke Width", None, -1))
        self.imgSettings_grpBx.setTitle(QtWidgets.QApplication.translate("ttStamperWindow", "*** IMAGE SETTINGS ***", None, -1))
        self.companyLogoSetting_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Sparx* Logo Percentage    ", None, -1))
        self.bvsa_bckgrd_color_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Before-After Background Color", None, -1))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.config_tab), QtWidgets.QApplication.translate("ttStamperWindow", "Cfg", None, -1))
        self.outputAsJPG_checkBox.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Output JPG", None, -1))
        self.srcOverwrite_checkBox.setText(QtWidgets.QApplication.translate("ttStamperWindow", "(!) Write to Same Folder", None, -1))
        self.autoDate_checkBox.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Auto Date (top R)", None, -1))
        self.unifyOutputs_checkBox.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Unify Dimensions:", None, -1))
        self.companyLogo_checkBox.setText(QtWidgets.QApplication.translate("ttStamperWindow", "Sparx* Logo (btm R)", None, -1))
        self.unifyOutputs_x_label.setText(QtWidgets.QApplication.translate("ttStamperWindow", "x", None, -1))
        self.browseOutput_btn.setText(QtWidgets.QApplication.translate("ttStamperWindow", ">..", None, -1))
        self.stampAll_btn.setText(QtWidgets.QApplication.translate("ttStamperWindow", "STAMP ALL", None, -1))

from widgets.ttsgraphicsview import TTSGraphicsView
from widgets.ttslistwidget_video import TTSListWidget_Video
from widgets.ttslistwidget import TTSListWidget
import ttStamper_resources_rc
